root: true

extends: "airbnb-base"
parser: "babel-eslint"

env:
  browser: true
  es6: true
  jasmine: true
  node: true

rules:
  import/no-extraneous-dependencies: ['error', {'devDependencies': true}]
  no-underscore-dangle: 0
